Use weakref.finalize instead of implementing custom __del__
Fixes errors when not closing EventIOFile before program exit:
```
Exception ignored in: <function EventIOFile.__del__ at 0x7f3ab6a558a0>
Traceback (most recent call last):
  File "/home/maxnoe/CTAO/pyeventio/src/eventio/base.py", line 159, in __del__
  File "/home/maxnoe/CTAO/pyeventio/src/eventio/base.py", line 150, in close
  File "/home/maxnoe/.local/conda/envs/cta-dev/lib/python3.12/subprocess.py", line 2220, in terminate
ImportError: sys.meta_path is None, Python is likely shutting down
```